### ISSUE TITLE
Change offsetSet function

### ISSUE THREAD

**Issue by ghost** [cygnite/cygnite-application#51]
Hello!

On PHP 7.2 + we need change this function to

`public function offsetSet($offset, $value = NULL)
    {
        if (is_null($offset)) {
            $this->stack[] = $value;
        } else {
            $this->stack[$offset] = $value;
        }
    }`

**Comment by sanjoydesk** [comment]
@jonasvreichel In which file ?

**Comment by ghost** [comment]
I did not remember, but I think it's on Container.
